name: 12 Pat Bump tag
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: ${{  github.event.pull_request.merged == true }} # Accessing the context for github 
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0 
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true